package amsPoDownload.pojo.data;

 /*
  * *------------- Suggest keeping this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 2022/04/11 0:0:0 
  * *     from Copybook: amsPoDownload
  * *          Template: pojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: cp1252
  * *     Generated for: JRecord Version 1200  
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   For the most, this Code should not be changed by hand you should:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *   * Use Organise Imports option in Eclipse (or equivalent function in other packages
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        2022/04/11  Initial version
  *     (Bruce Martin)
  */

import java.io.IOException;

import net.sf.JRecord.cgen.def.IArray1Dimension;
import net.sf.JRecord.cgen.def.IArray2Dimension;
import net.sf.JRecord.cgen.def.IArray3Dimension;
import net.sf.JRecord.cgen.def.IArrayAnyDimension;
import net.sf.JRecord.cgen.support.ArrayFieldDefinition1;
import net.sf.JRecord.Details.RecordDetail;

import net.sf.JRecord.cgen.impl.derSer.BasePojoConverter;
import net.sf.JRecord.def.IO.builders.ISchemaIOBuilder;

import net.sf.JRecord.Common.IFieldDetail;

import net.sf.JRecord.Details.AbstractLine;
import net.sf.JRecord.Details.LayoutDetail;
import net.sf.JRecord.Details.Line;
// The class IArrayFieldValue is not available in JRecord_Version_0.90_ReleaseCandidate_7
// IArrayFieldValue will be in JRecord_Version_0.90 expected release Nov/Dec 2018
import net.sf.JRecord.Details.fieldValue.IArrayFieldValue;
import net.sf.JRecord.Details.fieldValue.IFieldValueUpdLine;
import net.sf.JRecord.Details.fieldValue.LineFieldCreator;

public class ConvertLocationRecord extends BasePojoConverter<LineLocationRecordPojo> {
 
    public final IFieldValueUpdLine fuRecordType;

    public final IArray1Dimension arrayDcNumber;
    public final IArray1Dimension arrayPackQuantity;

// IArrayFieldValue and lfc.newArrayFieldValue(line will be in JRecord version to be in JRecord_Version_0.90  released Nov/Dec 2018
	 public final IArrayFieldValue uaDcNumber;
	 public final IArrayFieldValue uaPackQuantity;

                  
    public ConvertLocationRecord(ISchemaIOBuilder lineCreator) throws IOException {
        super(lineCreator);
        
        LayoutDetail schema = lineCreator.getLayout();
        FieldNamesAmspodownload.RecordLocationRecord fn
                   = FieldNamesAmspodownload.RECORD_LOCATION_RECORD;
        Line line = null;
        LineFieldCreator lfc = LineFieldCreator.getInstance();
                  
                   
        IFieldDetail fldRecordType = schema.getFieldFromName(fn.recordType);

        fuRecordType = lfc.newFieldValue(line, fldRecordType);

        RecordDetail record = schema.getRecord("Location-Record");

        ArrayFieldDefinition1 tmpArrayDcNumber = new ArrayFieldDefinition1(
                   new int[] {10},
                   record.getArrayFields(
                       record.getField(fn.dcNumber.get(0) ),
                       "DC-Number")      
        );
        arrayDcNumber = tmpArrayDcNumber;
        ArrayFieldDefinition1 tmpArrayPackQuantity = new ArrayFieldDefinition1(
                   new int[] {10},
                   record.getArrayFields(
                       record.getField(fn.packQuantity.get(0) ),
                       "Pack-Quantity")      
        );
        arrayPackQuantity = tmpArrayPackQuantity;

// IArrayFieldValue and lfc.newArrayFieldValue(line will be in JRecord version to be in JRecord_Version_0.90  released Nov/Dec 2018
	     uaDcNumber = lfc.newArrayFieldValue(line, tmpArrayDcNumber);
	     uaPackQuantity = lfc.newArrayFieldValue(line, tmpArrayPackQuantity);

    }
    
		

	
    private int  getDcNumberArrayLength(int indexNumber) {
        return arrayDcNumber.getArrayLength(indexNumber);
    }

    @Override
    public LineLocationRecordPojo toPojo(AbstractLine line) { 
        
        LineLocationRecordPojo pojo = new LineLocationRecordPojo();
        
        pojo.setRecordType(fuRecordType.setLine(line).asString());
	// false

                        
        uaDcNumber.setLine(line);
        uaPackQuantity.setLine(line);

        for (int idx1 = 0; idx1 < getDcNumberArrayLength(0); idx1++) {    
            pojo.setDcNumber(idx1, 
                       (short) uaDcNumber.setIndex(idx1).asInt());
            pojo.setPackQuantity(idx1, 
                       uaPackQuantity.setIndex(idx1).asInt());
        }
    

        return pojo;
    }

    @Override
    public void updateLine(AbstractLine line, LineLocationRecordPojo pojo) {
        
        fuRecordType.setLine(line).set(pojo.getRecordType());
    
        uaDcNumber.setLine(line);
        uaPackQuantity.setLine(line);

        for (int idx1 = 0; idx1 < getDcNumberArrayLength(0); idx1++) {    
           uaDcNumber.setIndex(idx1)
              .set(pojo.getDcNumber(idx1));
           uaPackQuantity.setIndex(idx1)
              .set(pojo.getPackQuantity(idx1));
        }
    
    }
    
	
}
