package amsPoDownload.pojo.data;

 /*
  * *------------- Suggest keeping this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 2022/04/11 0:0:0 
  * *     from Copybook: amsPoDownload
  * *          Template: pojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: cp1252
  * *     Generated for: JRecord Version 1200  
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   For the most, this Code should not be changed by hand you should:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *   * Use Organise Imports option in Eclipse (or equivalent function in other packages
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        2022/04/11  Initial version
  *     (Bruce Martin)
  */

import java.io.IOException;


import net.sf.JRecord.cgen.impl.derSer.BasePojoConverter;
import net.sf.JRecord.def.IO.builders.ISchemaIOBuilder;

import net.sf.JRecord.Common.IFieldDetail;

import net.sf.JRecord.Details.AbstractLine;
import net.sf.JRecord.Details.LayoutDetail;
import net.sf.JRecord.Details.Line;
import net.sf.JRecord.Details.fieldValue.IFieldValueUpdLine;
import net.sf.JRecord.Details.fieldValue.LineFieldCreator;

public class ConvertPoRecord extends BasePojoConverter<LinePoRecordPojo> {
 
    public final IFieldValueUpdLine fuRecordType;
    public final IFieldValueUpdLine fuSequenceNumber;
    public final IFieldValueUpdLine fuVendor;
    public final IFieldValueUpdLine fuPo;
    public final IFieldValueUpdLine fuEntryDate;
    public final IFieldValueUpdLine fuBeg01Code;
    public final IFieldValueUpdLine fuBeg02Code;
    public final IFieldValueUpdLine fuDepartment;
    public final IFieldValueUpdLine fuExpectedRecieptDate;
    public final IFieldValueUpdLine fuCancelByDate;
    public final IFieldValueUpdLine fuEdiType;
    public final IFieldValueUpdLine fuAddDate;
    public final IFieldValueUpdLine fuDepartmentName;
    public final IFieldValueUpdLine fuPrcoessType;
    public final IFieldValueUpdLine fuOrderType;




                  
    public ConvertPoRecord(ISchemaIOBuilder lineCreator) throws IOException {
        super(lineCreator);
        
        LayoutDetail schema = lineCreator.getLayout();
        FieldNamesAmspodownload.RecordPoRecord fn
                   = FieldNamesAmspodownload.RECORD_PO_RECORD;
        Line line = null;
        LineFieldCreator lfc = LineFieldCreator.getInstance();
                  
                   
        IFieldDetail fldRecordType = schema.getFieldFromName(fn.recordType);
        IFieldDetail fldSequenceNumber = schema.getFieldFromName(fn.sequenceNumber);
        IFieldDetail fldVendor = schema.getFieldFromName(fn.vendor);
        IFieldDetail fldPo = schema.getFieldFromName(fn.po);
        IFieldDetail fldEntryDate = schema.getFieldFromName(fn.entryDate);
        IFieldDetail fldBeg01Code = schema.getFieldFromName(fn.beg01Code);
        IFieldDetail fldBeg02Code = schema.getFieldFromName(fn.beg02Code);
        IFieldDetail fldDepartment = schema.getFieldFromName(fn.department);
        IFieldDetail fldExpectedRecieptDate = schema.getFieldFromName(fn.expectedRecieptDate);
        IFieldDetail fldCancelByDate = schema.getFieldFromName(fn.cancelByDate);
        IFieldDetail fldEdiType = schema.getFieldFromName(fn.ediType);
        IFieldDetail fldAddDate = schema.getFieldFromName(fn.addDate);
        IFieldDetail fldDepartmentName = schema.getFieldFromName(fn.departmentName);
        IFieldDetail fldPrcoessType = schema.getFieldFromName(fn.prcoessType);
        IFieldDetail fldOrderType = schema.getFieldFromName(fn.orderType);

        fuRecordType = lfc.newFieldValue(line, fldRecordType);
        fuSequenceNumber = lfc.newFieldValue(line, fldSequenceNumber);
        fuVendor = lfc.newFieldValue(line, fldVendor);
        fuPo = lfc.newFieldValue(line, fldPo);
        fuEntryDate = lfc.newFieldValue(line, fldEntryDate);
        fuBeg01Code = lfc.newFieldValue(line, fldBeg01Code);
        fuBeg02Code = lfc.newFieldValue(line, fldBeg02Code);
        fuDepartment = lfc.newFieldValue(line, fldDepartment);
        fuExpectedRecieptDate = lfc.newFieldValue(line, fldExpectedRecieptDate);
        fuCancelByDate = lfc.newFieldValue(line, fldCancelByDate);
        fuEdiType = lfc.newFieldValue(line, fldEdiType);
        fuAddDate = lfc.newFieldValue(line, fldAddDate);
        fuDepartmentName = lfc.newFieldValue(line, fldDepartmentName);
        fuPrcoessType = lfc.newFieldValue(line, fldPrcoessType);
        fuOrderType = lfc.newFieldValue(line, fldOrderType);





    }
    
	
    @Override
    public LinePoRecordPojo toPojo(AbstractLine line) { 
        
        LinePoRecordPojo pojo = new LinePoRecordPojo();
        
        pojo.setRecordType(fuRecordType.setLine(line).asString());
        pojo.setSequenceNumber(fuSequenceNumber.setLine(line).asBigDecimal());
        pojo.setVendor(fuVendor.setLine(line).asLong());
        pojo.setPo(fuPo.setLine(line).asLong());
        pojo.setEntryDate(fuEntryDate.setLine(line).asInt());
        pojo.setBeg01Code(fuBeg01Code.setLine(line).asString());
        pojo.setBeg02Code(fuBeg02Code.setLine(line).asString());
        pojo.setDepartment((short) fuDepartment.setLine(line).asInt());
        pojo.setExpectedRecieptDate(fuExpectedRecieptDate.setLine(line).asInt());
        pojo.setCancelByDate(fuCancelByDate.setLine(line).asInt());
        pojo.setEdiType(fuEdiType.setLine(line).asString());
        pojo.setAddDate(fuAddDate.setLine(line).asInt());
        pojo.setDepartmentName(fuDepartmentName.setLine(line).asString());
        pojo.setPrcoessType(fuPrcoessType.setLine(line).asString());
        pojo.setOrderType(fuOrderType.setLine(line).asString());
	// false

                        

        return pojo;
    }

    @Override
    public void updateLine(AbstractLine line, LinePoRecordPojo pojo) {
        
        fuRecordType.setLine(line).set(pojo.getRecordType());
        fuSequenceNumber.setLine(line).set(pojo.getSequenceNumber());
        fuVendor.setLine(line).set(pojo.getVendor());
        fuPo.setLine(line).set(pojo.getPo());
        fuEntryDate.setLine(line).set(pojo.getEntryDate());
        fuBeg01Code.setLine(line).set(pojo.getBeg01Code());
        fuBeg02Code.setLine(line).set(pojo.getBeg02Code());
        fuDepartment.setLine(line).set(pojo.getDepartment());
        fuExpectedRecieptDate.setLine(line).set(pojo.getExpectedRecieptDate());
        fuCancelByDate.setLine(line).set(pojo.getCancelByDate());
        fuEdiType.setLine(line).set(pojo.getEdiType());
        fuAddDate.setLine(line).set(pojo.getAddDate());
        fuDepartmentName.setLine(line).set(pojo.getDepartmentName());
        fuPrcoessType.setLine(line).set(pojo.getPrcoessType());
        fuOrderType.setLine(line).set(pojo.getOrderType());
    
    }
    
	
}
