package amsPoDownload.pojo.data;

 /*
  * *------------- Suggest keeping this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 2022/04/11 0:0:0 
  * *     from Copybook: amsPoDownload
  * *          Template: pojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: cp1252
  * *     Generated for: JRecord Version 1200  
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   For the most, this Code should not be changed by hand you should:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *   * Use Organise Imports option in Eclipse (or equivalent function in other packages
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        2022/04/11  Initial version
  *     (Bruce Martin)
  */

import java.io.IOException;


import net.sf.JRecord.cgen.impl.derSer.BasePojoConverter;
import net.sf.JRecord.def.IO.builders.ISchemaIOBuilder;

import net.sf.JRecord.Common.IFieldDetail;

import net.sf.JRecord.Details.AbstractLine;
import net.sf.JRecord.Details.LayoutDetail;
import net.sf.JRecord.Details.Line;
import net.sf.JRecord.Details.fieldValue.IFieldValueUpdLine;
import net.sf.JRecord.Details.fieldValue.LineFieldCreator;

public class ConvertProductRecord extends BasePojoConverter<LineProductRecordPojo> {
 
    public final IFieldValueUpdLine fuRecordType;
    public final IFieldValueUpdLine fuPackQty;
    public final IFieldValueUpdLine fuPackCost;
    public final IFieldValueUpdLine fuApn;
    public final IFieldValueUpdLine fuProduct;
    public final IFieldValueUpdLine fuPmgDtlTechKey;
    public final IFieldValueUpdLine fuCasePackId;
    public final IFieldValueUpdLine fuProductName;




                  
    public ConvertProductRecord(ISchemaIOBuilder lineCreator) throws IOException {
        super(lineCreator);
        
        LayoutDetail schema = lineCreator.getLayout();
        FieldNamesAmspodownload.RecordProductRecord fn
                   = FieldNamesAmspodownload.RECORD_PRODUCT_RECORD;
        Line line = null;
        LineFieldCreator lfc = LineFieldCreator.getInstance();
                  
                   
        IFieldDetail fldRecordType = schema.getFieldFromName(fn.recordType);
        IFieldDetail fldPackQty = schema.getFieldFromName(fn.packQty);
        IFieldDetail fldPackCost = schema.getFieldFromName(fn.packCost);
        IFieldDetail fldApn = schema.getFieldFromName(fn.apn);
        IFieldDetail fldProduct = schema.getFieldFromName(fn.product);
        IFieldDetail fldPmgDtlTechKey = schema.getFieldFromName(fn.pmgDtlTechKey);
        IFieldDetail fldCasePackId = schema.getFieldFromName(fn.casePackId);
        IFieldDetail fldProductName = schema.getFieldFromName(fn.productName);

        fuRecordType = lfc.newFieldValue(line, fldRecordType);
        fuPackQty = lfc.newFieldValue(line, fldPackQty);
        fuPackCost = lfc.newFieldValue(line, fldPackCost);
        fuApn = lfc.newFieldValue(line, fldApn);
        fuProduct = lfc.newFieldValue(line, fldProduct);
        fuPmgDtlTechKey = lfc.newFieldValue(line, fldPmgDtlTechKey);
        fuCasePackId = lfc.newFieldValue(line, fldCasePackId);
        fuProductName = lfc.newFieldValue(line, fldProductName);





    }
    
	
    @Override
    public LineProductRecordPojo toPojo(AbstractLine line) { 
        
        LineProductRecordPojo pojo = new LineProductRecordPojo();
        
        pojo.setRecordType(fuRecordType.setLine(line).asString());
        pojo.setPackQty(fuPackQty.setLine(line).asBigDecimal());
        pojo.setPackCost(fuPackCost.setLine(line).asBigDecimal());
        pojo.setApn(fuApn.setLine(line).asLong());
        pojo.setProduct(fuProduct.setLine(line).asInt());
        pojo.setPmgDtlTechKey(fuPmgDtlTechKey.setLine(line).asString());
        pojo.setCasePackId(fuCasePackId.setLine(line).asString());
        pojo.setProductName(fuProductName.setLine(line).asString());
	// false

                        

        return pojo;
    }

    @Override
    public void updateLine(AbstractLine line, LineProductRecordPojo pojo) {
        
        fuRecordType.setLine(line).set(pojo.getRecordType());
        fuPackQty.setLine(line).set(pojo.getPackQty());
        fuPackCost.setLine(line).set(pojo.getPackCost());
        fuApn.setLine(line).set(pojo.getApn());
        fuProduct.setLine(line).set(pojo.getProduct());
        fuPmgDtlTechKey.setLine(line).set(pojo.getPmgDtlTechKey());
        fuCasePackId.setLine(line).set(pojo.getCasePackId());
        fuProductName.setLine(line).set(pojo.getProductName());
    
    }
    
	
}
