package amsPoDownload.pojo.data;
 /*
  * *------------- Suggest keeping this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 2022/04/11 0:0:0 
  * *     from Copybook: amsPoDownload
  * *          Template: pojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: cp1252
  * *     Generated for: JRecord Version 1200  
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   For the most, this Code should not be changed by hand you should:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *   * Use Organise Imports option in Eclipse (or equivalent function in other packages
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        2022/04/11  Initial version
  *     (Bruce Martin)
  */
	

import java.math.BigDecimal;


/**
 * This class represents one Cobol Record type <b>PO-Record</b>
 * from COBOL copybook amsPoDownload
 */
public class LinePoRecordPojo extends LineAmspodownloadSchema 
 {

	
    private String recordType;
    private BigDecimal sequenceNumber;
    private long vendor;
    private long po;
    private int entryDate;
    private String beg01Code;
    private String beg02Code;
    private short department;
    private int expectedRecieptDate;
    private int cancelByDate;
    private String ediType;
    private int addDate;
    private String departmentName;
    private String prcoessType;
    private String orderType;




	/**
     * This class represents one Cobol Record type <b>PO-Record</b> from the file
	 * for COBOL copybook amsPoDownload
     */
    public LinePoRecordPojo() {
        super( amsPoDownload.pojo.definitions.DefsAmspodownload
                      .Records.PO_RECORD );
                      
	
    }

	/**
	 *  Get Cobol Field Record-Type (Position/Length 1/2)
	 */
    
    public String getRecordType() {
        return recordType;
    }
    
	/**
	 *  Set Cobol Field Record-Type (Position/Length 1/2
	 */
    
    public void setRecordType(String value) {
        this.recordType = value;
    }

	/**
	 *  Get Cobol Field Sequence-Number (Position/Length 3/5)
	 */
    
    public BigDecimal getSequenceNumber() {
        return sequenceNumber;
    }
    
	/**
	 *  Set Cobol Field Sequence-Number (Position/Length 3/5
	 */
    
    public void setSequenceNumber(BigDecimal value) {
        this.sequenceNumber = value;
    }

	/**
	 *  Get Cobol Field Vendor (Position/Length 8/10)
	 */
    
    public long getVendor() {
        return vendor;
    }
    
	/**
	 *  Set Cobol Field Vendor (Position/Length 8/10
	 */
    
    public void setVendor(long value) {
        this.vendor = value;
    }

	/**
	 *  Get Cobol Field PO (Position/Length 18/12)
	 */
    
    public long getPo() {
        return po;
    }
    
	/**
	 *  Set Cobol Field PO (Position/Length 18/12
	 */
    
    public void setPo(long value) {
        this.po = value;
    }

	/**
	 *  Get Cobol Field Entry-Date (Position/Length 30/6)
	 */
    
    public int getEntryDate() {
        return entryDate;
    }
    
	/**
	 *  Set Cobol Field Entry-Date (Position/Length 30/6
	 */
    
    public void setEntryDate(int value) {
        this.entryDate = value;
    }

	/**
	 *  Get Cobol Field beg01-code (Position/Length 44/2)
	 */
    
    public String getBeg01Code() {
        return beg01Code;
    }
    
	/**
	 *  Set Cobol Field beg01-code (Position/Length 44/2
	 */
    
    public void setBeg01Code(String value) {
        this.beg01Code = value;
    }

	/**
	 *  Get Cobol Field beg02-code (Position/Length 46/2)
	 */
    
    public String getBeg02Code() {
        return beg02Code;
    }
    
	/**
	 *  Set Cobol Field beg02-code (Position/Length 46/2
	 */
    
    public void setBeg02Code(String value) {
        this.beg02Code = value;
    }

	/**
	 *  Get Cobol Field Department (Position/Length 48/4)
	 */
    
    public short getDepartment() {
        return department;
    }
    
	/**
	 *  Set Cobol Field Department (Position/Length 48/4
	 */
    
    public void setDepartment(short value) {
        this.department = value;
    }

	/**
	 *  Get Cobol Field Expected-Reciept-Date (Position/Length 52/6)
	 */
    
    public int getExpectedRecieptDate() {
        return expectedRecieptDate;
    }
    
	/**
	 *  Set Cobol Field Expected-Reciept-Date (Position/Length 52/6
	 */
    
    public void setExpectedRecieptDate(int value) {
        this.expectedRecieptDate = value;
    }

	/**
	 *  Get Cobol Field Cancel-by-date (Position/Length 62/6)
	 */
    
    public int getCancelByDate() {
        return cancelByDate;
    }
    
	/**
	 *  Set Cobol Field Cancel-by-date (Position/Length 62/6
	 */
    
    public void setCancelByDate(int value) {
        this.cancelByDate = value;
    }

	/**
	 *  Get Cobol Field EDI-Type (Position/Length 68/1)
	 */
    
    public String getEdiType() {
        return ediType;
    }
    
	/**
	 *  Set Cobol Field EDI-Type (Position/Length 68/1
	 */
    
    public void setEdiType(String value) {
        this.ediType = value;
    }

	/**
	 *  Get Cobol Field Add-Date (Position/Length 69/6)
	 */
    
    public int getAddDate() {
        return addDate;
    }
    
	/**
	 *  Set Cobol Field Add-Date (Position/Length 69/6
	 */
    
    public void setAddDate(int value) {
        this.addDate = value;
    }

	/**
	 *  Get Cobol Field Department-Name (Position/Length 76/10)
	 */
    
    public String getDepartmentName() {
        return departmentName;
    }
    
	/**
	 *  Set Cobol Field Department-Name (Position/Length 76/10
	 */
    
    public void setDepartmentName(String value) {
        this.departmentName = value;
    }

	/**
	 *  Get Cobol Field Prcoess-Type (Position/Length 86/1)
	 */
    
    public String getPrcoessType() {
        return prcoessType;
    }
    
	/**
	 *  Set Cobol Field Prcoess-Type (Position/Length 86/1
	 */
    
    public void setPrcoessType(String value) {
        this.prcoessType = value;
    }

	/**
	 *  Get Cobol Field Order-Type (Position/Length 87/2)
	 */
    
    public String getOrderType() {
        return orderType;
    }
    
	/**
	 *  Set Cobol Field Order-Type (Position/Length 87/2
	 */
    
    public void setOrderType(String value) {
        this.orderType = value;
    }



	
	
	public LinePoRecordPojo asPoRecord() {
	    return this;
	}

}
