package amsPoDownload.pojo.data;
 /*
  * *------------- Suggest keeping this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 2022/04/11 0:0:0 
  * *     from Copybook: amsPoDownload
  * *          Template: pojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: cp1252
  * *     Generated for: JRecord Version 1200  
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   For the most, this Code should not be changed by hand you should:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *   * Use Organise Imports option in Eclipse (or equivalent function in other packages
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        2022/04/11  Initial version
  *     (Bruce Martin)
  */
	

import java.util.Arrays;


/**
 * This class represents one Cobol Record type <b>Location-Record</b>
 * from COBOL copybook amsPoDownload
 */
public class LineLocationRecordPojo extends LineAmspodownloadSchema 
 {

    private static final int[] LENGTH_DC_NUMBER = {10};
	
    private String recordType;

    private short[] dcNumber;        
    private int[] packQuantity;        



	/**
     * This class represents one Cobol Record type <b>Location-Record</b> from the file
	 * for COBOL copybook amsPoDownload
     */
    public LineLocationRecordPojo() {
        super( amsPoDownload.pojo.definitions.DefsAmspodownload
                      .Records.LOCATION_RECORD );
                      
	
        dcNumber  = new short[LENGTH_DC_NUMBER[0]] ;       	
        packQuantity  = new int[LENGTH_DC_NUMBER[0]] ;       	
        dcNumber  = new short[LENGTH_DC_NUMBER[0]];       	
        packQuantity  = new int[LENGTH_DC_NUMBER[0]];       	
        Arrays.fill(dcNumber , (short) 0);      	
        Arrays.fill(packQuantity , 0);      	

    }

	/**
	 *  Get Cobol Field Record-Type (Position/Length 1/2)
	 */
    
    public String getRecordType() {
        return recordType;
    }
    
	/**
	 *  Set Cobol Field Record-Type (Position/Length 1/2
	 */
    
    public void setRecordType(String value) {
        this.recordType = value;
    }


    
	/**
	 *  Get Cobol Array Field DC-Number Array Sizes: 10
	 */
    public short  getDcNumber(int idx1) {
        return dcNumber[idx1];
    }
  
	/**
	 *  Set Cobol Array Field DC-Number Array Sizes: 10
	 */
    
    public void setDcNumber(int idx1, short value) {
        dcNumber[idx1] = value;
    }

    
	/**
	 *  Get Cobol Array Field Pack-Quantity Array Sizes: 10
	 */
    public int  getPackQuantity(int idx1) {
        return packQuantity[idx1];
    }
  
	/**
	 *  Set Cobol Array Field Pack-Quantity Array Sizes: 10
	 */
    
    public void setPackQuantity(int idx1, int value) {
        packQuantity[idx1] = value;
    }


	
	/**
	 * Get the Array Sizes.
	 * @param indexNumber index of the array you want to get the size of
	 */
    public int  getDcNumberArrayLength(int indexNumber) {
        return LENGTH_DC_NUMBER[indexNumber];
    }
    
	
	
	public LineLocationRecordPojo asLocationRecord() {
	    return this;
	}

}
