package amsPoDownload.pojo.data;
 /*
  * *------------- Suggest keeping this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 2022/04/11 0:0:0 
  * *     from Copybook: amsPoDownload
  * *          Template: pojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: cp1252
  * *     Generated for: JRecord Version 1200  
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   For the most, this Code should not be changed by hand you should:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *   * Use Organise Imports option in Eclipse (or equivalent function in other packages
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        2022/04/11  Initial version
  *     (Bruce Martin)
  */
	

import java.math.BigDecimal;


/**
 * This class represents one Cobol Record type <b>Product-Record</b>
 * from COBOL copybook amsPoDownload
 */
public class LineProductRecordPojo extends LineAmspodownloadSchema 
 {

	
    private String recordType;
    private BigDecimal packQty;
    private BigDecimal packCost;
    private long apn;
    private int product;
    private String pmgDtlTechKey;
    private String casePackId;
    private String productName;




	/**
     * This class represents one Cobol Record type <b>Product-Record</b> from the file
	 * for COBOL copybook amsPoDownload
     */
    public LineProductRecordPojo() {
        super( amsPoDownload.pojo.definitions.DefsAmspodownload
                      .Records.PRODUCT_RECORD );
                      
	
    }

	/**
	 *  Get Cobol Field Record-Type (Position/Length 1/2)
	 */
    
    public String getRecordType() {
        return recordType;
    }
    
	/**
	 *  Set Cobol Field Record-Type (Position/Length 1/2
	 */
    
    public void setRecordType(String value) {
        this.recordType = value;
    }

	/**
	 *  Get Cobol Field Pack-Qty (Position/Length 3/9)
	 */
    
    public BigDecimal getPackQty() {
        return packQty;
    }
    
	/**
	 *  Set Cobol Field Pack-Qty (Position/Length 3/9
	 */
    
    public void setPackQty(BigDecimal value) {
        this.packQty = value;
    }

	/**
	 *  Get Cobol Field Pack-Cost (Position/Length 12/13)
	 */
    
    public BigDecimal getPackCost() {
        return packCost;
    }
    
	/**
	 *  Set Cobol Field Pack-Cost (Position/Length 12/13
	 */
    
    public void setPackCost(BigDecimal value) {
        this.packCost = value;
    }

	/**
	 *  Get Cobol Field APN (Position/Length 25/13)
	 */
    
    public long getApn() {
        return apn;
    }
    
	/**
	 *  Set Cobol Field APN (Position/Length 25/13
	 */
    
    public void setApn(long value) {
        this.apn = value;
    }

	/**
	 *  Get Cobol Field Product (Position/Length 39/8)
	 */
    
    public int getProduct() {
        return product;
    }
    
	/**
	 *  Set Cobol Field Product (Position/Length 39/8
	 */
    
    public void setProduct(int value) {
        this.product = value;
    }

	/**
	 *  Get Cobol Field pmg-dtl-tech-key (Position/Length 72/15)
	 */
    
    public String getPmgDtlTechKey() {
        return pmgDtlTechKey;
    }
    
	/**
	 *  Set Cobol Field pmg-dtl-tech-key (Position/Length 72/15
	 */
    
    public void setPmgDtlTechKey(String value) {
        this.pmgDtlTechKey = value;
    }

	/**
	 *  Get Cobol Field Case-Pack-id (Position/Length 87/15)
	 */
    
    public String getCasePackId() {
        return casePackId;
    }
    
	/**
	 *  Set Cobol Field Case-Pack-id (Position/Length 87/15
	 */
    
    public void setCasePackId(String value) {
        this.casePackId = value;
    }

	/**
	 *  Get Cobol Field Product-Name (Position/Length 102/50)
	 */
    
    public String getProductName() {
        return productName;
    }
    
	/**
	 *  Set Cobol Field Product-Name (Position/Length 102/50
	 */
    
    public void setProductName(String value) {
        this.productName = value;
    }



	
	
	public LineProductRecordPojo asProductRecord() {
	    return this;
	}

}
