package amsPoDownload.pojo.data;
 /*
  * *------------- Suggest keeping this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 2022/04/11 0:0:0 
  * *     from Copybook: amsPoDownload
  * *          Template: pojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: cp1252
  * *     Generated for: JRecord Version 1200  
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   For the most, this Code should not be changed by hand you should:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *   * Use Organise Imports option in Eclipse (or equivalent function in other packages
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        2022/04/11  Initial version
  *     (Bruce Martin)
  */

import amsPoDownload.pojo.definitions.DefsAmspodownload;

/**
  *  This abstract class is extended by all the indivual Record Classes<ul>
  *    <li>LinePoRecordPojo
  *    <li>LineProductRecordPojo
  *    <li>LineLocationRecordPojo
  * <ul>
  *
  *  You can use the <b>generatedRecordType</b> to get the RecordType.
  *  To process a line read in from the file
  * <pre>
  *    switch (line.generatedRecordType()) {
  *       case poRecord : process(line.asPoRecord);          break;
  *       case productRecord : process(line.asProductRecord);          break;
  *       case locationRecord : process(line.asLocationRecord);          break;
  *    } 
  * </pre>
  */
public abstract class LineAmspodownloadSchema  {
    private final DefsAmspodownload.Records record;
    
    protected LineAmspodownloadSchema (DefsAmspodownload.Records record) {
        this.record = record;
    }
    
	public final DefsAmspodownload.Records generatedRecordType() {
	    return record;
	}
	
	/**
	 * Return either the <b>actual Record</b> or <b>null</b>
	 * Depending on what record this is.
	 */
	public LinePoRecordPojo asPoRecord() {
	    return null;
	}
	
	/**
	 * Return either the <b>actual Record</b> or <b>null</b>
	 * Depending on what record this is.
	 */
	public LineProductRecordPojo asProductRecord() {
	    return null;
	}
	
	/**
	 * Return either the <b>actual Record</b> or <b>null</b>
	 * Depending on what record this is.
	 */
	public LineLocationRecordPojo asLocationRecord() {
	    return null;
	}
	
}
