package pojo.amsPoDownload.data;

 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 9.Jun.2001 0:0:0 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: pojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        9.Jun.2001  Initial version
  *     (Bruce Martin)
  */

import java.io.IOException;

import net.sf.JRecord.cgen.def.IArray1Dimension;
import net.sf.JRecord.cgen.impl.ArrayFieldDefinition1;
import net.sf.JRecord.Details.RecordDetail;

import net.sf.JRecord.cgen.impl.BasePojoConverter;
import net.sf.JRecord.def.IO.builders.ISchemaIOBuilder;

import net.sf.JRecord.Common.IFieldDetail;

import net.sf.JRecord.Details.AbstractLine;
import net.sf.JRecord.Details.LayoutDetail;
import net.sf.JRecord.Details.fieldValue.FieldValue;

public class ConvertLocationRecord extends BasePojoConverter<LineLocationRecordPojo> {
 
    public final IFieldDetail fldRecordType;

    public final IArray1Dimension arrayDcNumber;
    public final IArray1Dimension arrayPackQuantity;
                  
    public ConvertLocationRecord(ISchemaIOBuilder lineCreator) throws IOException {
        super(lineCreator);
        
        LayoutDetail schema = lineCreator.getLayout();
        FieldNamesAmspodownload.RecordLocationRecord fn
                   = FieldNamesAmspodownload.RECORD_LOCATION_RECORD;
                  
        fldRecordType = schema.getFieldFromName(fn.recordType);

        RecordDetail record = schema.getRecord("Location-Record");

        ArrayFieldDefinition1 tmpArrayDcNumber = new ArrayFieldDefinition1(
                   new int[] {10},
                   record.getArrayFields(
                       record.getField(fn.dcNumber.get(0) ),
                       "DC-Number")      
        );
        arrayDcNumber = tmpArrayDcNumber;
        ArrayFieldDefinition1 tmpArrayPackQuantity = new ArrayFieldDefinition1(
                   new int[] {10},
                   record.getArrayFields(
                       record.getField(fn.packQuantity.get(0) ),
                       "Pack-Quantity")      
        );
        arrayPackQuantity = tmpArrayPackQuantity;
    }

    /*
     * This method setField was introduced for use in Generated Code.
     * It is marked as depreciated to discourage its use outside generated code.
     * Suppressing `deprecation` because this is where the method is supposed to
     * be used. 
     */        
    @SuppressWarnings("deprecation")
    @Override
    public LineLocationRecordPojo toPojo(AbstractLine line) { 
        
        LineLocationRecordPojo pojo = new LineLocationRecordPojo();
        FieldValue u = new FieldValue(line, null);
        
        pojo.setRecordType(u.setField(fldRecordType).asString());   
    


        for (int idx1 = 0; idx1 < arrayDcNumber.getArrayLength(0); idx1++) {    
            pojo.setDcNumber(idx1,
                       (short) u.setField(arrayDcNumber.get(idx1)).asInt());
            pojo.setPackQuantity(idx1,
                       u.setField(arrayPackQuantity.get(idx1)).asInt());
        }
    

        return pojo;
    }

    /*
     * This method setField was introduced for use in Generated Code.
     * It is marked as depreciated to discourage its use outside generated code.
     * Suppressing `deprecation` because this is where the method is supposed to
     * be used. 
     */
    @SuppressWarnings("deprecation")
    @Override
    public void updateLine(AbstractLine line, LineLocationRecordPojo pojo) {
        
        FieldValue u = new FieldValue(line, null);
        
        u.setField(fldRecordType).set(pojo.getRecordType());
    
    
        for (int idx1 = 0; idx1 < arrayDcNumber.getArrayLength(0); idx1++) {    
           u.setField(arrayDcNumber.get(idx1))
              .set(pojo.getDcNumber(idx1));
           u.setField(arrayPackQuantity.get(idx1))
              .set(pojo.getPackQuantity(idx1));
        }
    
    }
	
}
