package example.ioBuilder.dtar020.example;
 /*
  *   Example program for DTAR020.cbl
  *   This class uses the JRecord project (https://sourceforge.net/projects/jrecord/)
  * -------------------------------------------------------------------
  *        
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 6 Nov 2018 12:47:9 
  * *     from Copybook: DTAR020.cbl
  * *          Template: javaPojo
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This class should be used as an example of reading/writing files
  *   using JRecord. You will need to modify the code to meet your
  *   needs. The Author of CodeGen (Bruce Martin) program takes no 
  *   responsibility for the accuracy of the generated code. 
  *
  *   Good Luck
  *              Bruce Martin
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        6 Nov 2018  Initial version
  *     (Bruce Martin)
  *
  * ------------------------------------------------------------------ 
  */

	

import net.sf.JRecord.cgen.def.IReader;

import example.ioBuilder.dtar020.data.LineDtar020JR;                                         
import example.ioBuilder.dtar020.data.LineDtar020Pojo;                                         
import example.ioBuilder.dtar020.io.IOBuilderDtar020;

	

/**
 * Read Cobol file using a Cobol Copybook (Dtar020).
 *
 * This Generated program is intended as an example of using JRecord
 * with generated classes.
 * You should regard it as a starting point and modify 
 * it according to your needs
 */
public final class ReadDtar020 {

    private String testDir        = "G:/temp/";
    private String salesFile      = testDir + "DTAR020.bin";

    private String copybookName   = "DTAR020.cbl"; 
 
    /**
     * Example of LineReader  classes
     */
    public ReadDtar020() {
    }
    
    public void byteArrayReader() {

    	LineDtar020JR line;
        int lineNum = 0;

        System.out.println();
        System.out.println(" ------ Reading via Byte Array ------");
        System.out.println();

        try {
            IOBuilderDtar020 ioBldr = new IOBuilderDtar020(copybookName);
            IReader<LineDtar020JR> reader = ioBldr.newReader(salesFile);  

            while ((line = reader.read()) != null) {
                lineNum += 1;
                System.out.println(
                              line.getKeycodeNo()
                      + " " + line.getStoreNo()
                      + " " + line.getDate()
                      + " " + line.getDeptNo()
                      + " " + line.getQtySold()
                      + " " + line.getSalePrice()
                   );
            }

            reader.close();
        } catch (Exception e) {
            System.out.println("~~> " + lineNum + " " + e);
            System.out.println();

            e.printStackTrace();
        }
    }
    
    public void pojoArrayReader() {

    	LineDtar020Pojo line;
        int lineNum = 0;
        
        System.out.println();
        System.out.println(" ------ Reading via POJO ------");
        System.out.println();

        try {
            IOBuilderDtar020 ioBldr = new IOBuilderDtar020(copybookName);
            IReader<LineDtar020Pojo> reader = ioBldr.newPojoReader(salesFile);  

            while ((line = reader.read()) != null) {
                lineNum += 1;
                System.out.println(
                              line.getKeycodeNo()
                      + " " + line.getStoreNo()
                      + " " + line.getDate()
                      + " " + line.getDeptNo()
                      + " " + line.getQtySold()
                      + " " + line.getSalePrice()
                   );
            }

            reader.close();
        } catch (Exception e) {
            System.out.println("~~> " + lineNum + " " + e);
            System.out.println();

            e.printStackTrace();
        }
    }

    
    public static void main(String[] args) {
        ReadDtar020 t = new ReadDtar020();

    	t.byteArrayReader();
   	t.pojoArrayReader();
    }
}

