package pojoWithInterface.amsPoDownload.example;
 /*
  *   Example program for amsPoDownload.cbl
  *   This class uses the JRecord project (https://sourceforge.net/projects/jrecord/)
  * -------------------------------------------------------------------
  *        
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 9.Jun.2001 0:0:0 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: pojoWithInterface
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This class should be used as an example of reading/writing files
  *   using JRecord. You will need to modify the code to meet your
  *   needs. The Author of CodeGen (Bruce Martin) program takes no 
  *   responsibility for the accuracy of the generated code. 
  *
  *   Good Luck
  *              Bruce Martin
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        9.Jun.2001  Initial version
  *     (Bruce Martin)
  *
  * ------------------------------------------------------------------ 
  */


import java.io.IOException;

import net.sf.JRecord.cgen.def.IWriter;
import net.sf.JRecord.cgen.impl.IoBuilder;

import pojoWithInterface.amsPoDownload.data.LineAmspodownloadSchema;

import pojoWithInterface.amsPoDownload.io.IoBuilderAmspodownload;
import pojoWithInterface.amsPoDownload.data.LinePoRecordPojo;
import pojoWithInterface.amsPoDownload.data.LineProductRecordPojo;
import pojoWithInterface.amsPoDownload.data.LineLocationRecordPojo;


/**
 * Write Cobol file using a Cobol Copybook (Amspodownload).
 *
 * This Generated program is intended as an example of using JRecord
 * rather than a useful program (that compiles - it wont).
 * You should regard it as a starting point and modify
 * it according to needs
 */
public final class WriteAmspodownload {


    private String outputFileName = "";
    private String copybookName   = "amsPoDownload.cbl";

    
    /**
     * Example of LineReader  classes
     */
    public WriteAmspodownload() {
        super();

        try {
            IoBuilder<LineAmspodownloadSchema> iob = IoBuilderAmspodownload.newIoBuilder(copybookName);
            IWriter<LineAmspodownloadSchema> writer = iob.newWriter(outputFileName);
 
            writer.write(createPoRecord(data));
            writer.write(createProductRecord(data));
            writer.write(createLocationRecord(data));

            writer.close();
       } catch (Exception e) {
             System.out.println();

            e.printStackTrace();
        }
    }


  /*
   *   The following code contains sample assignments for every 
   * field in the Cobol File. You should modify the code to suit
   * your needs.
   *   As I do not know where the data is coming from, I have used
   * SourceOfDataForTheCobolFile instead. You should replace this with your
   * class / classes  or remove it as needed.
   *   To put it another way, it time for you to start Coding
   */

    private LinePoRecordPojo createPoRecord(SourceOfDataForTheCobolFile data)
    throws IOException {

        LinePoRecordPojo line = new LinePoRecordPojo();

        line.setRecordType(data. ...);
        line.setSequenceNumber(data. ...);
        line.setVendor(data. ...);
        line.setPo(data. ...);
        line.setEntryDate(data. ...);
        line.setBeg01Code(data. ...);
        line.setBeg02Code(data. ...);
        line.setDepartment(data. ...);
        line.setExpectedRecieptDate(data. ...);
        line.setCancelByDate(data. ...);
        line.setEdiType(data. ...);
        line.setAddDate(data. ...);
        line.setDepartmentName(data. ...);
        line.setPrcoessType(data. ...);
        line.setOrderType(data. ...);


        return line;
    }

    private LineProductRecordPojo createProductRecord(SourceOfDataForTheCobolFile data)
    throws IOException {

        LineProductRecordPojo line = new LineProductRecordPojo();

        line.setRecordType(data. ...);
        line.setPackQty(data. ...);
        line.setPackCost(data. ...);
        line.setApn(data. ...);
        line.setProduct(data. ...);
        line.setPmgDtlTechKey(data. ...);
        line.setCasePackId(data. ...);
        line.setProductName(data. ...);


        return line;
    }

    private LineLocationRecordPojo createLocationRecord(SourceOfDataForTheCobolFile data)
    throws IOException {

        LineLocationRecordPojo line = new LineLocationRecordPojo();

        line.setRecordType(data. ...);

        line.setDcNumber(0, data. ...);
        line.setPackQuantity(0, data. ...);

        return line;
    }

    public static void main(String[] args) {
        new WriteAmspodownload();
    }
}

