package lineWrapper.amsPoDownload.data;

 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 9.Jun.2001 0:0:0 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: lineWrapper
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        9.Jun.2001  Initial version
  *     (Bruce Martin)
  */

/**
 *  This is a <i>LineWrapper</i> class - it wraps JRecord Line
 *  makes it look like a Java Bean and implements the relavent
 *  interfaces
 */
 


import net.sf.JRecord.Details.AbstractLine;
import net.sf.JRecord.Details.IGetByteData;
import net.sf.JRecord.Details.Line;
import net.sf.JRecord.Details.CsvLine;


public class LineLocationRecordJR implements IGetByteData {
   
    private AbstractLine line; 

    private static FieldNamesAmspodownload.RecordLocationRecord fn
                   = FieldNamesAmspodownload.RECORD_LOCATION_RECORD;

    private int[] sizeDcNumber = {10};
        

    
    public String getRecordType() {
        return line.getFieldValue(fn.recordType).asString();
    }
    
    
    public void setRecordType(String value) {
        this.line.getFieldValue(fn.recordType).set(value);
    }


    
    public short  getDcNumber(int idx1) {
        return (short) (line.getFieldValue(fn.dcNumber.get(idx1))).asInt();
    }
    
    
    
    public void setDcNumber(int idx1, short value) {
        (line.getFieldValue(fn.dcNumber.get(idx1))).set(value);
    }

    
    public int  getPackQuantity(int idx1) {
        return (line.getFieldValue(fn.packQuantity.get(idx1))).asInt();
    }
    
    
    
    public void setPackQuantity(int idx1, int value) {
        (line.getFieldValue(fn.packQuantity.get(idx1))).set(value);
    }

	
    public int  getDcNumberArrayLength(int indexNumber) {
        return sizeDcNumber[indexNumber];
    }


    @Override
    public byte[] getData() {
        return line.getData();  
    }

    @Override
    public void setData(byte[] data) {

        if (line instanceof Line || line instanceof CsvLine) {
            line.setData(data);
        } else {
            throw new RuntimeException("Invalid line for setdata");
        }
    }
    
    public LineLocationRecordJR setLine(AbstractLine l) {
    	line = l;
    	return this;
    }
    
    public AbstractLine getLine() {
        return line;
    }
}

