package lineWrapper.amsPoDownload.data;

 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 9.Jun.2001 0:0:0 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: lineWrapper
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        9.Jun.2001  Initial version
  *     (Bruce Martin)
  */

/**
 *  This is a <i>LineWrapper</i> class - it wraps JRecord Line
 *  makes it look like a Java Bean and implements the relavent
 *  interfaces
 */
 

import java.math.BigDecimal;

import net.sf.JRecord.Details.AbstractLine;
import net.sf.JRecord.Details.IGetByteData;
import net.sf.JRecord.Details.Line;
import net.sf.JRecord.Details.CsvLine;


public class LinePoRecordJR implements IGetByteData {
   
    private AbstractLine line; 

    private static FieldNamesAmspodownload.RecordPoRecord fn
                   = FieldNamesAmspodownload.RECORD_PO_RECORD;

        

    
    public String getRecordType() {
        return line.getFieldValue(fn.recordType).asString();
    }
    
    
    public void setRecordType(String value) {
        this.line.getFieldValue(fn.recordType).set(value);
    }

    
    public BigDecimal getSequenceNumber() {
        return line.getFieldValue(fn.sequenceNumber).asBigDecimal();
    }
    
    
    public void setSequenceNumber(BigDecimal value) {
        this.line.getFieldValue(fn.sequenceNumber).set(value);
    }

    
    public long getVendor() {
        return line.getFieldValue(fn.vendor).asLong();
    }
    
    
    public void setVendor(long value) {
        this.line.getFieldValue(fn.vendor).set(value);
    }

    
    public long getPo() {
        return line.getFieldValue(fn.po).asLong();
    }
    
    
    public void setPo(long value) {
        this.line.getFieldValue(fn.po).set(value);
    }

    
    public String getEntryDate() {
        return line.getFieldValue(fn.entryDate).asString();
    }
    
    
    public void setEntryDate(String value) {
        this.line.getFieldValue(fn.entryDate).set(value);
    }

    
    public String getBeg01Code() {
        return line.getFieldValue(fn.beg01Code).asString();
    }
    
    
    public void setBeg01Code(String value) {
        this.line.getFieldValue(fn.beg01Code).set(value);
    }

    
    public String getBeg02Code() {
        return line.getFieldValue(fn.beg02Code).asString();
    }
    
    
    public void setBeg02Code(String value) {
        this.line.getFieldValue(fn.beg02Code).set(value);
    }

    
    public String getDepartment() {
        return line.getFieldValue(fn.department).asString();
    }
    
    
    public void setDepartment(String value) {
        this.line.getFieldValue(fn.department).set(value);
    }

    
    public String getExpectedRecieptDate() {
        return line.getFieldValue(fn.expectedRecieptDate).asString();
    }
    
    
    public void setExpectedRecieptDate(String value) {
        this.line.getFieldValue(fn.expectedRecieptDate).set(value);
    }

    
    public String getCancelByDate() {
        return line.getFieldValue(fn.cancelByDate).asString();
    }
    
    
    public void setCancelByDate(String value) {
        this.line.getFieldValue(fn.cancelByDate).set(value);
    }

    
    public String getEdiType() {
        return line.getFieldValue(fn.ediType).asString();
    }
    
    
    public void setEdiType(String value) {
        this.line.getFieldValue(fn.ediType).set(value);
    }

    
    public String getAddDate() {
        return line.getFieldValue(fn.addDate).asString();
    }
    
    
    public void setAddDate(String value) {
        this.line.getFieldValue(fn.addDate).set(value);
    }

    
    public String getDepartmentName() {
        return line.getFieldValue(fn.departmentName).asString();
    }
    
    
    public void setDepartmentName(String value) {
        this.line.getFieldValue(fn.departmentName).set(value);
    }

    
    public String getPrcoessType() {
        return line.getFieldValue(fn.prcoessType).asString();
    }
    
    
    public void setPrcoessType(String value) {
        this.line.getFieldValue(fn.prcoessType).set(value);
    }

    
    public String getOrderType() {
        return line.getFieldValue(fn.orderType).asString();
    }
    
    
    public void setOrderType(String value) {
        this.line.getFieldValue(fn.orderType).set(value);
    }


	


    @Override
    public byte[] getData() {
        return line.getData();  
    }

    @Override
    public void setData(byte[] data) {

        if (line instanceof Line || line instanceof CsvLine) {
            line.setData(data);
        } else {
            throw new RuntimeException("Invalid line for setdata");
        }
    }
    
    public LinePoRecordJR setLine(AbstractLine l) {
    	line = l;
    	return this;
    }
    
    public AbstractLine getLine() {
        return line;
    }
}

