package example.ioBuilder.dtar020.data;

 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 6 Nov 2018 12:47:9 
  * *     from Copybook: DTAR020.cbl
  * *          Template: javaPojo
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        6 Nov 2018  Initial version
  *     (Bruce Martin)
  */

import example.ioBuilder.dtar020.def.IDtar020;  
import example.ioBuilder.dtar020.def.IDtar020Upd;  

public class CodeDtar020 {

     public static void assignDtar020(IDtar020Upd to, IDtar020 from) {

        to.setKeycodeNo(from.getKeycodeNo());
        to.setStoreNo(from.getStoreNo());
        to.setDate(from.getDate());
        to.setDeptNo(from.getDeptNo());
        to.setQtySold(from.getQtySold());
        to.setSalePrice(from.getSalePrice());
	
     }
     
}
