package lineWrapperPojo.AmsPoDownload.example;
 /*
  *   Example program for amsPoDownload.cbl
  *   This class uses the JRecord project (https://sourceforge.net/projects/jrecord/)
  * -------------------------------------------------------------------
  *        
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 6 Nov 2018 8:28:53 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: lineWrapperPojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This class should be used as an example of reading/writing files
  *   using JRecord. You will need to modify the code to meet your
  *   needs. The Author of CodeGen (Bruce Martin) program takes no 
  *   responsibility for the accuracy of the generated code. 
  *
  *   Good Luck
  *              Bruce Martin
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        6 Nov 2018  Initial version
  *     (Bruce Martin)
  *
  * ------------------------------------------------------------------ 
  */


import java.io.IOException;

import net.sf.JRecord.JRecordInterface1;
import net.sf.JRecord.Details.AbstractLine;
import net.sf.JRecord.Common.Constants;
import net.sf.JRecord.External.CopybookLoader;
import net.sf.JRecord.def.IO.builders.ICobolIOBuilder;

import net.sf.JRecord.IO.AbstractLineWriter;


import lineWrapperPojo.AmsPoDownload.data.LinePoRecordJR;
import lineWrapperPojo.AmsPoDownload.data.LineProductRecordJR;
import lineWrapperPojo.AmsPoDownload.data.LineLocationRecordJR;


/**
 * Write Cobol file using a Cobol Copybook (Amspodownload).
 *
 * This Generated program is intended as an example of using JRecord
 * rather than a useful program (that compiles - it wont).
 * You should regard it as a starting point and modify
 * it according to needs
 */
public final class WriteAmspodownload {


    private String outputFileName = "";
    private String copybookName   = "amsPoDownload.cbl";

    private LinePoRecordJR linePoRecordJR = new LinePoRecordJR();
    private LineProductRecordJR lineProductRecordJR = new LineProductRecordJR();
    private LineLocationRecordJR lineLocationRecordJR = new LineLocationRecordJR();



    /**
     * Example of LineReader  classes
     */
    public WriteAmspodownload() {
        super();

        try {
            ICobolIOBuilder iob = JRecordInterface1.COBOL
                                .newIOBuilder(copybookName)
                                   //.setFont("") // Think about specifying an encoding !!!
                                   .setFileOrganization(Constants.IO_BIN_TEXT)
                                   .setSplitCopybook(CopybookLoader.SPLIT_01_LEVEL)
         //TODO   --    Setup/Check record Selection !!!
         //TODO     .setRecordSelection( "PO-Record", ExternalFieldSelection.newFieldSelection("field-name", "value to test"))  
         //TODO     .setRecordSelection( "Product-Record", ExternalFieldSelection.newFieldSelection("field-name", "value to test"))  
         //TODO     .setRecordSelection( "Location-Record", ExternalFieldSelection.newFieldSelection("field-name", "value to test"))  
                                       ;  
            AbstractLineWriter writer = iob.newWriter(outputFileName);

            writer.write(createPoRecord(iob, data));
            writer.write(createProductRecord(iob, data));
            writer.write(createLocationRecord(iob, data));

            writer.close();
        } catch (Exception e) {
             System.out.println();

            e.printStackTrace();
        }
    }


  /*
   *   The following code contains sample assignments for every 
   * field in the Cobol File. You should modify the code to suit
   * your needs.
   *   As I do not know where the data is coming from, I have used
   * SourceOfDataForTheCobolFile instead. You should replace this with your
   * class / classes  or remove it as needed.
   *   To put it another way, it time for you to start Coding
   */

    private AbstractLine createPoRecord(ICobolIOBuilder iob, SourceOfDataForTheCobolFile data)
    throws IOException {
        AbstractLine line = iob.newLine();
        linePoRecordJR.setLine(line);

        linePoRecordJR.setRecordType(data. ...);
        linePoRecordJR.setSequenceNumber(data. ...);
        linePoRecordJR.setVendor(data. ...);
        linePoRecordJR.setPo(data. ...);
        linePoRecordJR.setEntryDate(data. ...);
        linePoRecordJR.setBeg01Code(data. ...);
        linePoRecordJR.setBeg02Code(data. ...);
        linePoRecordJR.setDepartment(data. ...);
        linePoRecordJR.setExpectedRecieptDate(data. ...);
        linePoRecordJR.setCancelByDate(data. ...);
        linePoRecordJR.setEdiType(data. ...);
        linePoRecordJR.setAddDate(data. ...);
        linePoRecordJR.setDepartmentName(data. ...);
        linePoRecordJR.setPrcoessType(data. ...);
        linePoRecordJR.setOrderType(data. ...);


        return line;
    }

    private AbstractLine createProductRecord(ICobolIOBuilder iob, SourceOfDataForTheCobolFile data)
    throws IOException {
        AbstractLine line = iob.newLine();
        lineProductRecordJR.setLine(line);

        lineProductRecordJR.setRecordType(data. ...);
        lineProductRecordJR.setPackQty(data. ...);
        lineProductRecordJR.setPackCost(data. ...);
        lineProductRecordJR.setApn(data. ...);
        lineProductRecordJR.setProduct(data. ...);
        lineProductRecordJR.setPmgDtlTechKey(data. ...);
        lineProductRecordJR.setCasePackId(data. ...);
        lineProductRecordJR.setProductName(data. ...);


        return line;
    }

    private AbstractLine createLocationRecord(ICobolIOBuilder iob, SourceOfDataForTheCobolFile data)
    throws IOException {
        AbstractLine line = iob.newLine();
        lineLocationRecordJR.setLine(line);

        lineLocationRecordJR.setRecordType(data. ...);

        lineLocationRecordJR.setDcNumber(0, data. ...);
        lineLocationRecordJR.setPackQuantity(0, data. ...);

        return line;
    }

    public static void main(String[] args) {
        new WriteAmspodownload();
    }
}

