package lineWrapperPojo.amsPoDownload.def;
 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 9.Jun.2001 0:0:0 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: lineWrapperPojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        9.Jun.2001  Initial version
  *     (Bruce Martin)
  */

import java.math.BigDecimal;

public interface IPoRecordUpd {

    public abstract void setRecordType(String value);
    public abstract void setSequenceNumber(BigDecimal value);
    public abstract void setVendor(long value);
    public abstract void setPo(long value);
    public abstract void setEntryDate(String value);
    public abstract void setBeg01Code(String value);
    public abstract void setBeg02Code(String value);
    public abstract void setDepartment(String value);
    public abstract void setExpectedRecieptDate(String value);
    public abstract void setCancelByDate(String value);
    public abstract void setEdiType(String value);
    public abstract void setAddDate(String value);
    public abstract void setDepartmentName(String value);
    public abstract void setPrcoessType(String value);
    public abstract void setOrderType(String value);




    public abstract void set(IPoRecord value);
}

