package example.ioBuilder.dtar020.schema;
 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 6 Nov 2018 12:47:8 
  * *     from Copybook: DTAR020.cbl
  * *          Template: schemaClass
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        6 Nov 2018  Initial version
  *     (Bruce Martin)
  */

import net.sf.JRecord.Common.CommonBits;
import net.sf.JRecord.Common.Constants;
import net.sf.JRecord.Details.LayoutDetail;
import net.sf.JRecord.Details.RecordDetail;

public class SchemaDtar020 {

    public final RecordDtar020 recordDtar020;
    
    public final LayoutDetail schema;
    
    public SchemaDtar020() {
    
 	recordDtar020 = new RecordDtar020();
        
        RecordDetail[] recs = {
                recordDtar020.record,
        };

        String recordSepString = ""; 
        byte[] recordSep = CommonBits.getEolBytes( null, recordSepString, "cp037");
        schema = new LayoutDetail(
                      "DTAR020", recs, "", 
                      Constants.rtBinaryRecord, recordSep, recordSepString, 
                      "cp037", null, Constants.IO_FIXED_LENGTH_RECORDS);
        
        recordDtar020.updateRecordSelection(schema);
    }
    
    public SchemaDtar020(LayoutDetail schema) {
        this.recordDtar020 = new RecordDtar020(schema, schema.getRecord("DTAR020"));

        this.schema = schema;
    }
}

