package stdPojo.dtar020.data;
 /*
  *          Field Name's for DTAR020.cbl
  * ------------------------------------------------------------------   
  *
  *   This class holds the field names of Cobol-Copybook DTAR020.cbl
  *   It will allow you use code completion on <i>Cobol Field Names</i> in your
  *   java Programs 
  *        
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 9 Aug 2017   :  :   
  * *     from Copybook: DTAR020.cbl
  * *          Template: stdPojo
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        9 Aug 2017  Initial version
  *     (Bruce Martin)
  */


public class FieldNamesDtar020 {

    public static final RecordDtar020 RECORD_DTAR020 = new RecordDtar020();

    public static class RecordDtar020 {
       public final String keycodeNo = "DTAR020-KEYCODE-NO";
       public final String storeNo = "DTAR020-STORE-NO";
       public final String date = "DTAR020-DATE";
       public final String deptNo = "DTAR020-DEPT-NO";
       public final String qtySold = "DTAR020-QTY-SOLD";
       public final String salePrice = "DTAR020-SALE-PRICE";
	
    }


}

