package stdPojo.dtar020.data;
 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 9 Aug 2017   :  :   
  * *     from Copybook: DTAR020.cbl
  * *          Template: stdPojo
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        9 Aug 2017  Initial version
  *     (Bruce Martin)
  */

import java.math.BigDecimal;

import stdPojo.dtar020.def.IDtar020;
import stdPojo.dtar020.def.IDtar020Pojo;



public class LineDtar020Pojo  implements IDtar020Pojo {

    private String keycodeNo;
    private short storeNo;
    private int date;
    private short deptNo;
    private int qtySold;
    private BigDecimal salePrice;



    @Override
    public String getKeycodeNo() {
        return keycodeNo;
    }
    
    @Override
    public void setKeycodeNo(String value) {
        this.keycodeNo = value;
    }

    @Override
    public short getStoreNo() {
        return storeNo;
    }
    
    @Override
    public void setStoreNo(short value) {
        this.storeNo = value;
    }

    @Override
    public int getDate() {
        return date;
    }
    
    @Override
    public void setDate(int value) {
        this.date = value;
    }

    @Override
    public short getDeptNo() {
        return deptNo;
    }
    
    @Override
    public void setDeptNo(short value) {
        this.deptNo = value;
    }

    @Override
    public int getQtySold() {
        return qtySold;
    }
    
    @Override
    public void setQtySold(int value) {
        this.qtySold = value;
    }

    @Override
    public BigDecimal getSalePrice() {
        return salePrice;
    }
    
    @Override
    public void setSalePrice(BigDecimal value) {
        this.salePrice = value;
    }



	
	
    public void set(IDtar020 value) {
        CodeDtar020
            .assignDtar020(
                this, value);
    }

}
