package example.ioBuilder.amsPoDownload.schema;
 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 6 Nov 2018 18:59:18 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: schemaClass
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        6 Nov 2018  Initial version
  *     (Bruce Martin)
  */
import net.sf.JRecord.Common.Constants;
import net.sf.JRecord.Common.FieldDetail;
import net.sf.JRecord.Common.IFieldDetail;
import net.sf.JRecord.Details.LayoutDetail;
import net.sf.JRecord.Details.RecordDetail;
import net.sf.JRecord.Types.Type;

public class RecordPoRecord {

    public static final String RECORD_NAME = "PO-Record";
    
    public final IFieldDetail fldRecordType;
    public final IFieldDetail fldSequenceNumber;
    public final IFieldDetail fldVendor;
    public final IFieldDetail fldPo;
    public final IFieldDetail fldEntryDate;
    public final IFieldDetail fldBeg01Code;
    public final IFieldDetail fldBeg02Code;
    public final IFieldDetail fldDepartment;
    public final IFieldDetail fldExpectedRecieptDate;
    public final IFieldDetail fldCancelByDate;
    public final IFieldDetail fldEdiType;
    public final IFieldDetail fldAddDate;
    public final IFieldDetail fldDepartmentName;
    public final IFieldDetail fldPrcoessType;
    public final IFieldDetail fldOrderType;


    public final RecordDetail record;
    
    private final String font;
    
    public RecordPoRecord() {
       FieldDetail[] flds = new FieldDetail[15];
       int i = 0;
       
       font = "";
       fldRecordType = createField(flds, i++, "Record-Type", Type.ftChar, 1, 2, 0);
       fldSequenceNumber = createField(flds, i++, "Sequence-Number", Type.ftAssumedDecimalPositive, 3, 5, 3);
       fldVendor = createField(flds, i++, "Vendor", Type.ftNumZeroPaddedPositive, 8, 10, 0);
       fldPo = createField(flds, i++, "PO", Type.ftNumZeroPaddedPositive, 18, 12, 0);
       fldEntryDate = createField(flds, i++, "Entry-Date", Type.ftChar, 30, 6, 0);
       fldBeg01Code = createField(flds, i++, "beg01-code", Type.ftChar, 44, 2, 0);
       fldBeg02Code = createField(flds, i++, "beg02-code", Type.ftChar, 46, 2, 0);
       fldDepartment = createField(flds, i++, "Department", Type.ftChar, 48, 4, 0);
       fldExpectedRecieptDate = createField(flds, i++, "Expected-Reciept-Date", Type.ftChar, 52, 6, 0);
       fldCancelByDate = createField(flds, i++, "Cancel-by-date", Type.ftChar, 62, 6, 0);
       fldEdiType = createField(flds, i++, "EDI-Type", Type.ftChar, 68, 1, 0);
       fldAddDate = createField(flds, i++, "Add-Date", Type.ftChar, 69, 6, 0);
       fldDepartmentName = createField(flds, i++, "Department-Name", Type.ftChar, 76, 10, 0);
       fldPrcoessType = createField(flds, i++, "Prcoess-Type", Type.ftChar, 86, 1, 0);
       fldOrderType = createField(flds, i++, "Order-Type", Type.ftChar, 87, 2, 0);

      String t = "	"; 	
      if (t == "\t") {
          t = "<tab>";
      }
      record = new RecordDetail(RECORD_NAME,
                   null,
                   Constants.rtBinaryRecord, t, "",
                   font, flds, 0);
      record.setParentRecordIndex( -1);
         


    }
    
    public RecordPoRecord(LayoutDetail l, RecordDetail r) {
    
        font = l.getFontName();
        record = r;
        
        fldRecordType = l.getFieldFromName("Record-Type");        
        fldSequenceNumber = l.getFieldFromName("Sequence-Number");        
        fldVendor = l.getFieldFromName("Vendor");        
        fldPo = l.getFieldFromName("PO");        
        fldEntryDate = l.getFieldFromName("Entry-Date");        
        fldBeg01Code = l.getFieldFromName("beg01-code");        
        fldBeg02Code = l.getFieldFromName("beg02-code");        
        fldDepartment = l.getFieldFromName("Department");        
        fldExpectedRecieptDate = l.getFieldFromName("Expected-Reciept-Date");        
        fldCancelByDate = l.getFieldFromName("Cancel-by-date");        
        fldEdiType = l.getFieldFromName("EDI-Type");        
        fldAddDate = l.getFieldFromName("Add-Date");        
        fldDepartmentName = l.getFieldFromName("Department-Name");        
        fldPrcoessType = l.getFieldFromName("Prcoess-Type");        
        fldOrderType = l.getFieldFromName("Order-Type");        


    }
    
    public void updateRecordSelection(LayoutDetail l) {
    }
    
    private FieldDetail createField(
                FieldDetail[] flds, int idx,
                String name,
                int type,
                int pos,
                int len,
                int decimal) {
        flds[idx] = FieldDetail.newFixedWidthField(name, type, pos, len, decimal, font);
        return flds[idx];
    }
}
