package example.ioBuilder.amsPoDownload.def;
 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 6 Nov 2018 8:27:10 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: pojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        6 Nov 2018  Initial version
  *     (Bruce Martin)
  */

import java.util.HashMap;

public class DefsAmspodownload {

	private static final HashMap<String, Records> recordMap = new HashMap<String, Records>();
	
    public enum Records {
         PO_RECORD("PO-Record")
        ,PRODUCT_RECORD("Product-Record")
        ,LOCATION_RECORD("Location-Record")
	;		

		private final String recName;
		Records(String recName) {
			this.recName = recName;
			
			recordMap.put(recName.toLowerCase(), this);
		}
	}
	
	public static Records recordFromString(String recName) {
		if (recName == null) { return null;}
		return recordMap.get(recName.toLowerCase());
	}
}
