package pojoWithInterface.dtar027.def;
 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 4 Nov 2018 21:32:19 
  * *     from Copybook: DTAR027.cbl
  * *          Template: pojoWithInterface
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        4 Nov 2018  Initial version
  *     (Bruce Martin)
  */

import java.math.BigDecimal;

public interface IDtar027Upd {

    public abstract void setKeycodeNo(String value);
    public abstract void setQtySold(int value);
    public abstract void setSalePrice(BigDecimal value);




    public abstract void set(IDtar027 value);
}

