package example.ioBuilder.dtar020.example;
 /*
  *   Example program for DTAR020.cbl
  *   This class uses the JRecord project (https://sourceforge.net/projects/jrecord/)
  * -------------------------------------------------------------------
  *        
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 6 Nov 2018 12:47:8 
  * *     from Copybook: DTAR020.cbl
  * *          Template: schemaClass
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This class should be used as an example of reading/writing files
  *   using JRecord. You will need to modify the code to meet your
  *   needs. The Author of CodeGen (Bruce Martin) program takes no 
  *   responsibility for the accuracy of the generated code. 
  *
  *   Good Luck
  *              Bruce Martin
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        6 Nov 2018  Initial version
  *     (Bruce Martin)
  *
  * ------------------------------------------------------------------ 
  */


import java.io.IOException;

import net.sf.JRecord.JRecordInterface1;
import net.sf.JRecord.Details.AbstractLine;
import net.sf.JRecord.Common.Constants;
import net.sf.JRecord.External.CopybookLoader;
import net.sf.JRecord.def.IO.builders.ICobolIOBuilder;

import net.sf.JRecord.IO.AbstractLineWriter;

import example.ioBuilder.dtar020.schema.RecordDtar020;
import example.ioBuilder.dtar020.schema.SchemaDtar020;


/**
 * Write Cobol file using a Cobol Copybook (Dtar020).
 *
 * This Generated program is intended as an example of using JRecord
 * rather than a useful program (that compiles - it wont).
 * You should regard it as a starting point and modify 
 * it according to needs
 */
public final class WriteDtar020 {

    private String testDir        = "G:/temp/";
    private String salesFileOut   = testDir + "DTAR020out.bin";
    private String copybookName   = "DTAR020.cbl"; 

    private RecordDtar020 rDtar020;
    
    /**
     * Example of LineReader  classes
     */
    public WriteDtar020() {
        super();

        try {
            ICobolIOBuilder iob = JRecordInterface1.COBOL
                                .newIOBuilder(copybookName)
                                   .setFont("cp037") 
                                   .setFileOrganization(Constants.IO_FIXED_LENGTH)
                                   .setSplitCopybook(CopybookLoader.SPLIT_NONE)
                                   .setDropCopybookNameFromFields(true)
                                       ;  
            SchemaDtar020 schemaDtar020
                    = new SchemaDtar020(iob.getLayout()); 
            rDtar020 = schemaDtar020.recordDtar020;
            AbstractLineWriter writer = iob.newWriter(salesFileOut);
 
            writer.write(createDtar020(iob, data));

            writer.close();
        } catch (Exception e) {
             System.out.println();

            e.printStackTrace();
        }
    }


  /*
   *   The following code contains sample assignments for every 
   * field in the Cobol File. You should modify the code to suit
   * your needs.
   *   As I do not know where the data is coming from, I have used
   * SourceOfDataForTheCobolFile instead. You should replace this with your
   * class / classes  or remove it as needed.
   *   To put it another way, it time for you to start Coding
   */

    private AbstractLine createDtar020(ICobolIOBuilder iob, SourceOfDataForTheCobolFile data) 
    throws IOException {
        AbstractLine l = iob.newLine();    
        
        l.getFieldValue(rDtar020.fldKeycodeNo).set(data. ...);
        l.getFieldValue(rDtar020.fldStoreNo).set(data. ...);
        l.getFieldValue(rDtar020.fldDate).set(data. ...);
        l.getFieldValue(rDtar020.fldDeptNo).set(data. ...);
        l.getFieldValue(rDtar020.fldQtySold).set(data. ...);
        l.getFieldValue(rDtar020.fldSalePrice).set(data. ...);
	
    
        return l;
    }

    public static void main(String[] args) {
        new WriteDtar020();
    }
}

