package amsPoDownload.pojo.definitions;
 /*
  * *------------- Suggest keeping this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 2022/04/11 0:0:0 
  * *     from Copybook: amsPoDownload
  * *          Template: pojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: cp1252
  * *     Generated for: JRecord Version 1200  
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   For the most, this Code should not be changed by hand you should:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *   * Use Organise Imports option in Eclipse (or equivalent function in other packages
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        2022/04/11  Initial version
  *     (Bruce Martin)
  */

import java.util.HashMap;

/**
 * This class defines the various records in the schema in a enum.
 * There is a method <b>recordFromString</b> to convert the Record name
 * to the enum
 */
public class DefsAmspodownload {

	private static final HashMap<String, Records> recordMap = new HashMap<String, Records>();
	
	/**
	 * Enum for all the record Types
	 */
    public enum Records {
         PO_RECORD("PO-Record")
        ,PRODUCT_RECORD("Product-Record")
        ,LOCATION_RECORD("Location-Record")
	;		

		private final String recName;
		Records(String recName) {
			this.recName = recName;
			
			recordMap.put(recName.toLowerCase(), this);
		}
	}
	
	/**
	 * Convert the Record name (Cobol Name) to the equivalent enum value
	 */
	public static Records recordFromString(String recName) {
		if (recName == null) { return null;}
		return recordMap.get(recName.toLowerCase());
	}
}
