package lineWrapperPojo.AmsPoDownload.data;

 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 6 Nov 2018 8:28:53 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: lineWrapperPojo
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        6 Nov 2018  Initial version
  *     (Bruce Martin)
  */

import lineWrapperPojo.AmsPoDownload.def.IPoRecord;  
import lineWrapperPojo.AmsPoDownload.def.IPoRecordUpd;  
import lineWrapperPojo.AmsPoDownload.def.IProductRecord;  
import lineWrapperPojo.AmsPoDownload.def.IProductRecordUpd;  
import lineWrapperPojo.AmsPoDownload.def.ILocationRecord;  
import lineWrapperPojo.AmsPoDownload.def.ILocationRecordUpd;  

public class CodeAmspodownload {

     public static void assignPoRecord(IPoRecordUpd to, IPoRecord from) {

        to.setRecordType(from.getRecordType());
        to.setSequenceNumber(from.getSequenceNumber());
        to.setVendor(from.getVendor());
        to.setPo(from.getPo());
        to.setEntryDate(from.getEntryDate());
        to.setBeg01Code(from.getBeg01Code());
        to.setBeg02Code(from.getBeg02Code());
        to.setDepartment(from.getDepartment());
        to.setExpectedRecieptDate(from.getExpectedRecieptDate());
        to.setCancelByDate(from.getCancelByDate());
        to.setEdiType(from.getEdiType());
        to.setAddDate(from.getAddDate());
        to.setDepartmentName(from.getDepartmentName());
        to.setPrcoessType(from.getPrcoessType());
        to.setOrderType(from.getOrderType());
	
     }
     
     public static void assignProductRecord(IProductRecordUpd to, IProductRecord from) {

        to.setRecordType(from.getRecordType());
        to.setPackQty(from.getPackQty());
        to.setPackCost(from.getPackCost());
        to.setApn(from.getApn());
        to.setProduct(from.getProduct());
        to.setPmgDtlTechKey(from.getPmgDtlTechKey());
        to.setCasePackId(from.getCasePackId());
        to.setProductName(from.getProductName());
	
     }
     
     public static void assignLocationRecord(ILocationRecordUpd to, ILocationRecord from) {

        to.setRecordType(from.getRecordType());
	
        for (int idx1 = 0; idx1 < from.getDcNumberArrayLength(0); idx1++) {	
            to.setDcNumber(
                   idx1,  
                   from.getDcNumber(idx1));
            to.setPackQuantity(
                   idx1,  
                   from.getPackQuantity(idx1));
        }
	
     }
     
}
