package example.ioBuilder.amsPoDownload.data;
 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 5 Nov 2018 16:40:56 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: pojoWithInterface
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        5 Nov 2018  Initial version
  *     (Bruce Martin)
  */

import example.ioBuilder.amsPoDownload.def.DefsAmspodownload;

import example.ioBuilder.amsPoDownload.def.IAmspodownloadSchema;

public abstract class LineAmspodownloadSchema     implements IAmspodownloadSchema  {
    private final DefsAmspodownload.Records record;
    
    protected LineAmspodownloadSchema (DefsAmspodownload.Records record) {
        this.record = record;
    }
    
	public final DefsAmspodownload.Records generatedRecordType() {
	    return record;
	}
	
	public LinePoRecordPojo asPoRecord() {
	    return null;
	}
	
	public LineProductRecordPojo asProductRecord() {
	    return null;
	}
	
	public LineLocationRecordPojo asLocationRecord() {
	    return null;
	}
	
}
