package example.ioBuilder.amsPoDownload.data;
 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 5 Nov 2018 16:40:56 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: pojoWithInterface
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        5 Nov 2018  Initial version
  *     (Bruce Martin)
  */
	
/**
 * This class is the Java representation of one record in the file
 */

import java.math.BigDecimal;

import example.ioBuilder.amsPoDownload.def.IProductRecord;
import example.ioBuilder.amsPoDownload.def.IProductRecordPojo;



public class LineProductRecordPojo extends LineAmspodownloadSchema 
implements IProductRecordPojo {

    private String recordType;
    private BigDecimal packQty;
    private BigDecimal packCost;
    private long apn;
    private int product;
    private String pmgDtlTechKey;
    private String casePackId;
    private String productName;


    public LineProductRecordPojo() {
        super( example.ioBuilder.amsPoDownload.def.DefsAmspodownload
                      .Records.PRODUCT_RECORD );
                      
	
    }

    @Override
    public String getRecordType() {
        return recordType;
    }
    
    @Override
    public void setRecordType(String value) {
        this.recordType = value;
    }

    @Override
    public BigDecimal getPackQty() {
        return packQty;
    }
    
    @Override
    public void setPackQty(BigDecimal value) {
        this.packQty = value;
    }

    @Override
    public BigDecimal getPackCost() {
        return packCost;
    }
    
    @Override
    public void setPackCost(BigDecimal value) {
        this.packCost = value;
    }

    @Override
    public long getApn() {
        return apn;
    }
    
    @Override
    public void setApn(long value) {
        this.apn = value;
    }

    @Override
    public int getProduct() {
        return product;
    }
    
    @Override
    public void setProduct(int value) {
        this.product = value;
    }

    @Override
    public String getPmgDtlTechKey() {
        return pmgDtlTechKey;
    }
    
    @Override
    public void setPmgDtlTechKey(String value) {
        this.pmgDtlTechKey = value;
    }

    @Override
    public String getCasePackId() {
        return casePackId;
    }
    
    @Override
    public void setCasePackId(String value) {
        this.casePackId = value;
    }

    @Override
    public String getProductName() {
        return productName;
    }
    
    @Override
    public void setProductName(String value) {
        this.productName = value;
    }



	
    public void set(IProductRecord pojo) {
       recordType = pojo.getRecordType();
       packQty = pojo.getPackQty();
       packCost = pojo.getPackCost();
       apn = pojo.getApn();
       product = pojo.getProduct();
       pmgDtlTechKey = pojo.getPmgDtlTechKey();
       casePackId = pojo.getCasePackId();
       productName = pojo.getProductName();
    
    }
	
	public LineProductRecordPojo asProductRecord() {
	    return this;
	}

}
