package example.ioBuilder.amsPoDownload.data;
 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 5 Nov 2018 16:40:56 
  * *     from Copybook: amsPoDownload.cbl
  * *          Template: pojoWithInterface
  * *             Split: 01   
  * * File Organization: Text   
  * *              Font: 
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        5 Nov 2018  Initial version
  *     (Bruce Martin)
  */
	
/**
 * This class is the Java representation of one record in the file
 */

import java.math.BigDecimal;

import example.ioBuilder.amsPoDownload.def.IPoRecord;
import example.ioBuilder.amsPoDownload.def.IPoRecordPojo;



public class LinePoRecordPojo extends LineAmspodownloadSchema 
implements IPoRecordPojo {

    private String recordType;
    private BigDecimal sequenceNumber;
    private long vendor;
    private long po;
    private String entryDate;
    private String beg01Code;
    private String beg02Code;
    private String department;
    private String expectedRecieptDate;
    private String cancelByDate;
    private String ediType;
    private String addDate;
    private String departmentName;
    private String prcoessType;
    private String orderType;


    public LinePoRecordPojo() {
        super( example.ioBuilder.amsPoDownload.def.DefsAmspodownload
                      .Records.PO_RECORD );
                      
	
    }

    @Override
    public String getRecordType() {
        return recordType;
    }
    
    @Override
    public void setRecordType(String value) {
        this.recordType = value;
    }

    @Override
    public BigDecimal getSequenceNumber() {
        return sequenceNumber;
    }
    
    @Override
    public void setSequenceNumber(BigDecimal value) {
        this.sequenceNumber = value;
    }

    @Override
    public long getVendor() {
        return vendor;
    }
    
    @Override
    public void setVendor(long value) {
        this.vendor = value;
    }

    @Override
    public long getPo() {
        return po;
    }
    
    @Override
    public void setPo(long value) {
        this.po = value;
    }

    @Override
    public String getEntryDate() {
        return entryDate;
    }
    
    @Override
    public void setEntryDate(String value) {
        this.entryDate = value;
    }

    @Override
    public String getBeg01Code() {
        return beg01Code;
    }
    
    @Override
    public void setBeg01Code(String value) {
        this.beg01Code = value;
    }

    @Override
    public String getBeg02Code() {
        return beg02Code;
    }
    
    @Override
    public void setBeg02Code(String value) {
        this.beg02Code = value;
    }

    @Override
    public String getDepartment() {
        return department;
    }
    
    @Override
    public void setDepartment(String value) {
        this.department = value;
    }

    @Override
    public String getExpectedRecieptDate() {
        return expectedRecieptDate;
    }
    
    @Override
    public void setExpectedRecieptDate(String value) {
        this.expectedRecieptDate = value;
    }

    @Override
    public String getCancelByDate() {
        return cancelByDate;
    }
    
    @Override
    public void setCancelByDate(String value) {
        this.cancelByDate = value;
    }

    @Override
    public String getEdiType() {
        return ediType;
    }
    
    @Override
    public void setEdiType(String value) {
        this.ediType = value;
    }

    @Override
    public String getAddDate() {
        return addDate;
    }
    
    @Override
    public void setAddDate(String value) {
        this.addDate = value;
    }

    @Override
    public String getDepartmentName() {
        return departmentName;
    }
    
    @Override
    public void setDepartmentName(String value) {
        this.departmentName = value;
    }

    @Override
    public String getPrcoessType() {
        return prcoessType;
    }
    
    @Override
    public void setPrcoessType(String value) {
        this.prcoessType = value;
    }

    @Override
    public String getOrderType() {
        return orderType;
    }
    
    @Override
    public void setOrderType(String value) {
        this.orderType = value;
    }



	
    public void set(IPoRecord pojo) {
       recordType = pojo.getRecordType();
       sequenceNumber = pojo.getSequenceNumber();
       vendor = pojo.getVendor();
       po = pojo.getPo();
       entryDate = pojo.getEntryDate();
       beg01Code = pojo.getBeg01Code();
       beg02Code = pojo.getBeg02Code();
       department = pojo.getDepartment();
       expectedRecieptDate = pojo.getExpectedRecieptDate();
       cancelByDate = pojo.getCancelByDate();
       ediType = pojo.getEdiType();
       addDate = pojo.getAddDate();
       departmentName = pojo.getDepartmentName();
       prcoessType = pojo.getPrcoessType();
       orderType = pojo.getOrderType();
    
    }
	
	public LinePoRecordPojo asPoRecord() {
	    return this;
	}

}
