package xLineWrapper.dtar027.data;
 /*
  *          Field Name's for DTAR027.cbl
  * ------------------------------------------------------------------   
  *
  *   This class holds the field names of Cobol-Copybook DTAR027.cbl
  *   It will allow you use code completion on <i>Cobol Field Names</i> in your
  *   java Programs 
  *        
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 6 Nov 2018 11:13:42 
  * *     from Copybook: DTAR027.cbl
  * *          Template: xLineWrapper
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        6 Nov 2018  Initial version
  *     (Bruce Martin)
  */


public class FieldNamesDtar027 {

    public static final RecordDtar027 RECORD_DTAR027 = new RecordDtar027();

    public static class RecordDtar027 {
       public final String keycodeNo = "DTAR027-KEYCODE-NO";
       public final String qtySold = "DTAR027-QTY-SOLD";
       public final String salePrice = "DTAR027-SALE-PRICE";
	
    }


}

