package pojoWithInterface.dtar027.example;
 /*
  *   Example program for DTAR027.cbl
  *   This class uses the JRecord project (https://sourceforge.net/projects/jrecord/)
  * -------------------------------------------------------------------
  *        
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 4 Nov 2018 15:55:47 
  * *     from Copybook: DTAR027.cbl
  * *          Template: pojoWithInterface
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This class should be used as an example of reading/writing files
  *   using JRecord. You will need to modify the code to meet your
  *   needs. The Author of CodeGen (Bruce Martin) program takes no 
  *   responsibility for the accuracy of the generated code. 
  *
  *   Good Luck
  *              Bruce Martin
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        4 Nov 2018  Initial version
  *     (Bruce Martin)
  *
  * ------------------------------------------------------------------ 
  */


import java.io.IOException;

import net.sf.JRecord.cgen.def.IWriter;
import net.sf.JRecord.cgen.impl.IoBuilder;


import pojoWithInterface.dtar027.io.IoBuilderDtar027;
import pojoWithInterface.dtar027.data.LineDtar027Pojo;


/**
 * Write Cobol file using a Cobol Copybook (Dtar027).
 *
 * This Generated program is intended as an example of using JRecord
 * rather than a useful program (that compiles - it wont).
 * You should regard it as a starting point and modify
 * it according to needs
 */
public final class WriteDtar027 {


    private String outputFileName = "";
    private String copybookName   = "DTAR027.cbl";

    
    /**
     * Example of LineReader  classes
     */
    public WriteDtar027() {
        super();

        try {
            IoBuilder<LineDtar027Pojo> iob = IoBuilderDtar027.newIoBuilder(copybookName);
            IWriter<LineDtar027Pojo> writer = iob.newWriter(outputFileName);
 
            writer.write(createDtar027(data));

            writer.close();
       } catch (Exception e) {
             System.out.println();

            e.printStackTrace();
        }
    }


  /*
   *   The following code contains sample assignments for every 
   * field in the Cobol File. You should modify the code to suit
   * your needs.
   *   As I do not know where the data is coming from, I have used
   * SourceOfDataForTheCobolFile instead. You should replace this with your
   * class / classes  or remove it as needed.
   *   To put it another way, it time for you to start Coding
   */

    private LineDtar027Pojo createDtar027(SourceOfDataForTheCobolFile data)
    throws IOException {

        LineDtar027Pojo line = new LineDtar027Pojo();

        line.setKeycodeNo(data. ...);
        line.setQtySold(data. ...);
        line.setSalePrice(data. ...);


        return line;
    }

    public static void main(String[] args) {
        new WriteDtar027();
    }
}

