package pojo.dtar020.data;
 /*
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 9.Jun.2001 0:0:0 
  * *     from Copybook: DTAR020.cbl
  * *          Template: pojo
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This Code should not be changed you should, either:
  *   * Rerun CodeGen to regenerate it 
  *   * Fix CodeGen and rerun CodeGen
  *
  *   Please supply any program fixes/enhancements/documentation
  *   back to the JRecord project (https://sourceforge.net/projects/jrecord/)
  *   so other people can benefit !!!
  * 
  *
  *          Bruce Martin (JRecord / CodeGen Author) 
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        9.Jun.2001  Initial version
  *     (Bruce Martin)
  */
	
/**
 * This class is the Java representation of one record in the file
 */

import java.math.BigDecimal;


public class LineDtar020Pojo 
 {

    private String keycodeNo;
    private short storeNo;
    private int date;
    private short deptNo;
    private int qtySold;
    private BigDecimal salePrice;



    
    public String getKeycodeNo() {
        return keycodeNo;
    }
    
    
    public void setKeycodeNo(String value) {
        this.keycodeNo = value;
    }

    
    public short getStoreNo() {
        return storeNo;
    }
    
    
    public void setStoreNo(short value) {
        this.storeNo = value;
    }

    
    public int getDate() {
        return date;
    }
    
    
    public void setDate(int value) {
        this.date = value;
    }

    
    public short getDeptNo() {
        return deptNo;
    }
    
    
    public void setDeptNo(short value) {
        this.deptNo = value;
    }

    
    public int getQtySold() {
        return qtySold;
    }
    
    
    public void setQtySold(int value) {
        this.qtySold = value;
    }

    
    public BigDecimal getSalePrice() {
        return salePrice;
    }
    
    
    public void setSalePrice(BigDecimal value) {
        this.salePrice = value;
    }



	

}
