package pojoWithInterface.dtar027.example;
 /*
  *   Example program for DTAR027.cbl
  *   This class uses the JRecord project (https://sourceforge.net/projects/jrecord/)
  * -------------------------------------------------------------------
  *        
  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 10 Aug 2017 9:58:18 
  * *     from Copybook: DTAR027.cbl
  * *          Template: pojoWithInterface
  * *             Split: None   
  * * File Organization: FixedWidth   
  * *              Font: cp037
  * *   
  * *    CodeGen Author: Bruce Martin
  * *-----------------------------------------------------------------
  *
  *   This class should be used as an example of reading/writing files
  *   using JRecord. You will need to modify the code to meet your
  *   needs. The Author of CodeGen (Bruce Martin) program takes no 
  *   responsibility for the accuracy of the generated code. 
  *
  *   Good Luck
  *              Bruce Martin
  *
  * ------------------------------------------------------------------
  * v01  CodeGen        10 Aug 2017  Initial version
  *     (Bruce Martin)
  *
  * ------------------------------------------------------------------ 
  */

	

import java.io.IOException;

import net.sf.JRecord.cgen.def.IReader;
import net.sf.JRecord.cgen.impl.IoBuilder;


import pojoWithInterface.dtar027.io.IoBuilderDtar027;
import pojoWithInterface.dtar027.data.LineDtar027Pojo;


/**
 * Read Cobol file using a Cobol Copybook (Dtar027).
 *
 * This Generated program is intended as an example of using JRecord
 * rather than a useful program (that compiles - it wont).
 * You should regard it as a starting point and modify
 * it according to needs
 */
public final class ReadDtar027 {

    private String dataFile     = "";
    private String copybookName = "DTAR027.cbl";

    /**
     * Example of Using a PojoReader  classes
     */
    public ReadDtar027() {
        super();

        IReader<LineDtar027Pojo> reader = null;
        int lineNum = 0;
        try {
            IoBuilder<LineDtar027Pojo> iob = IoBuilderDtar027.newIoBuilder(copybookName);
            LineDtar027Pojo line;

            reader = iob.newReader(dataFile);
            
            while ((line = reader.read()) != null) {
                lineNum += 1;
                
               System.out.println(
                              line.getKeycodeNo()
                      + " " + line.getQtySold()
                      + " " + line.getSalePrice()
                   );
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    public static void main(String[] args) {
        new ReadDtar027();
    }
}

